JwtSettings:
  Issuer: "https://hospitalmanagementapi.com"
  Audience: "https://hospitalmanagementfrontend.com"
  Key: "Gx+NV3/HjB6Y8sJEXrwFh6L+wV4CvX0mnblKh4sQktc="

Logging:
  LogLevel:
    Default: "Information"
    Microsoft.AspNetCore: "Warning"

ConnectionStrings:
  DefaultConnection: "Server=ASGARDIAN-FORGE\\SQLEXPRESS;Database=HospitalManagement;Trusted_Connection=True;TrustServerCertificate=True;"

AllowedHosts: "*"
